skillcrush/105-practice

- advice/franferrell-advice.html
- css/franferrell-style.css
- index.html
> Add Fran's advice

- advice/advice-katieb.html
- css/advice-katieb.css
- index.html
Second submission for this exercise. Gets easier each time.
> changes to 105-practice

- advice/kellys-advice.html
- css/kellys-style.css
- index.html
> new advice html and css pages

- advice/kandisflick-advice.html
- css/kandisflick-style.css
- index.html
Add changes for the purpose of practicing using Github.
> First push

- advice/graciem-advice.html
- css/graciem-style.css
- index.html
Hi skillcrush people ... added advice.html, style.css and link in index.html with username GracieM
> Added advice.html, style.css and link in index.html for GracieM

- advice/taylortatro-advice.html
- css/taylortatro-style.css
- index.html
> Taylorjtatro

- advice/jordans-advice.html
- css/jordans-advice.css
- index.html
> Jordan's Advice section

- advice/kerrymcshanekay-advice.html
- css/style-kmk-v2.css
- index.html
> Experiment

- advice/john-advice.html
- css/john-style.css
- index.html
Some advice I would like to share. :]
> john advice and css addon

- advice/seanr-advice.html
- css/seanr-advice.css
- index.html
updated my advice link on index.html file.
> 20181005 sr

- advice/seanr-advice.html
- css/seanr-advice.css
- index.html
Just wanted to add some advice.
> 20181004 sr

- advice/tsw-advice.html
- css/tsw-style.css
- index.html
This was a fun assignment.  My page isn't that fancy, but I like what I wrote.  Hope you do too!
> TSW Advice

- advice/cataylwin-advice.html
- css/caylwin-style.css
- index.html
Attempting pull request for 105-practice project
> First draft html and css for my advice page - project 105

- advice/ericavarlese-advice.html
- css/ericavarlese-style.css
- index.html
Created a page for my advice, and styling my advice.
> Add Erica's Advice

- advice/kerrymcshanekay-advice.html
Just made minor punctuation change so I could finish the lesson and create a new pull request. I guess I had synced everything in the last step so had nothing to compare across forks (hence the small change).
> minor punctuation change in body

- advice/katrina-advice.html
- css/katrina-style.css
- index.html
> Experiment 105

- advice/aubreys-advice.html
- css/aubreys-advice.css
- index.html
> Aubreys Advice html and css

- advice/stuartgee-advice.html
- css/stuartgee-advice.css
- index.html
> added stuartgee advice page

- advice/adriannek-advice.html
- css/advice-adriannek-style.css
- index.html
> Adriannekadvice

- advice/jenn-advice.html
- css/jenn-style.css
- index.html
Added Jenn's advice to the index
> Experiments

- advice/kristingrigsbyadvice.html
- css/kristingrigsbyadvice.css
- index.html
I have added a page for kristin grigsby's advice.
> kristin grigsby's advice

- advice/maryam-advice.html
- css/maryam-style.css
- index.html
Some advice I have for newbies
> do over advice page

- advice/sabh-advice.html
- css/sabh-advise-style.css
- index.html
This is soooooo important it needs to be part of the master!! (role playing over here)
> add SH advice files

- advice/mssherilles-advice.html
- css/mssherilles-style.css
- index.html
Please let me know if this is not correct. Lots of uncertainty going through the exercises as I myself am a newbie!   Thanks!
P.S. Instead of "Able to merge" as in the example, I show "X Can't automatically merge."  Is that normal?
> Add my advice

- advice/rebs-advice-oct-2018.html
- css/reb-style-oct-2018.css
- index.html
This is my second attempt at submitting a pull request for this lesson. Fingers crossed this works ;)
> created advice HTML page, added styles file, added link to index.html

- advice/richkeyzor-advice.html
- css/richkeyzor-advice.css
- index.html
PR for my advice that I would like to add. Please merge unless any questions for me :)
> Add richs-advice branch

- advice/mirela-advice.html
- css/mirela-advice.css
- index.html
I would appreciate some feedback :)
Thank you
> Experimental

- .gitignore
- advice/andrekolmeijer-advice.html
- css/andrekolmeijer-styles.css
- index.html
Hi, I made the changes below and love for them to be pulled into the upstream version:
Created my html and css files and added them in the right folders;
Added the link to my files in the index.html file and cleaned it up (so it looks neat again); and,
Modified the .gitignore file to ignore Google Drive icons.
> Added andrekolmeijer and adjusted .gitignore

- advice/rick-advice.html
- css/rick-style.css
- index.html
Also removed some spaces to make the index a bit tidier.
> Added Rick's advice

- advice/meganwillard-advice.html
- css/meganwillard-styles.css
Some advice I would love to share.
> added new file

- advice/erinp-advice.html
- css/erinp-styles.css
- index.html
> Add Erin P's advice

- advice/jillianh-advice.html
- css/jillianh-style.css
please review and let me know if this works.
> my skillcrush repo css and html and css edits

- advice/meil-advice.html
- css/meil-style.css
- index.html
Some advice I would like to share!
> Add Mei's advice

- advice/julearenas-advice.html
- css/julearenas-styles.css
- index.html
> julearenas advice html/css

- advice/nicole-advice.html
- css/nicole-advice.css
- index.html
Oops, sent the last one too early. Here's the right version with my edits.
> changed header fonts and colors

- advice/caseyb-advice.html
- css/caseyb-styles.css
- index.html
Hi!
I'd like to submit this branch for inclusion in the main code.  Thank you for taking the time to consider it and look it over!
> Experimenting

- advice/kranthi-advice.html
- css/kranthi-style.css
- index.html
Hey ! I've added my share of advice ! Let me know if you find any issues
> added Kranthi-advice.html and Kranthi-style.css

- advice/bentta-advice.html
- css/bentta-style.css
- index.html
> Ugly advice page edits

- advice/JWYCadvice.html
- css/JWYCstyle.css
- index.html
i think the code should be clean and good to go :)
> please add JWYC advice 

- advice/jevera-advice.html
- css/jevera-advice-style.css
- index.html
Some advice I would love to share :)
> Jever's Advice

- advice/jimmy-advice.html
- css/jimmy-style.css
- index.html
Just adding my part with a little bit of style. :)
> Jimmy edit

- advice/bridgetc-advice.html
- css/bridgetc-style.css
- index.html
> bridgetmcar advice

- advice/rmoord-advice.html
- css/rmoord-style.css
- index.html
I added my rmoord advice to html and css
> added rmoord advice to html and css

- advice/tatyananovell-advice.html
- css/tatyananovel-styles.css
- index.html
Some changes I would like to share.
> tatyana's changes

- advice/rachelp-advice.html
- css/rachelp-style.css
- index.html
I'd like to add some advice to the project!
> added my advice page and styled it

- advice/carmenp-advice.html
- css/carmenp-style.css
- index.html
added my own advice html and css, updated index.html
> adding my advice

- advice/pascal-advice.html
- css/pascal-style.css
- index.html
Advice site, css stylesheet for it and the link on the main index.html
> added my personal advice site.

- advice/katherinerosa-advice.html
- css/advice-katherinerosa.css
- index.html
Some advice I would love to share.
> Add Katherine's advice

- advice/cazden-advice.html
- css/cazden-advice-style.css
- index.html
Advice for N00bs from a N00b :)
> added advice from cazden

- advice/jamieb-advice.html
- css/jamieb-advice.css
- index.html
Hi there,
I'd love to merge my code, if that's okay :)
> Jamie B's Advice page

- advice/kasandras-advice.html
- css/kasandras-style.css
- index.html
Resubmission of my advice page.
> added kasandras advice

- advice/gabriella-advice.html
- css/gabriella-style.css
- index.html
Most of this is stylistic edits.
> add 2 files

- advice/amberc-advice.html
- css/amberc-styles.css
- index.html
> Add AmberC's Advice

- advice/reggie-advice.html
- css/reggie-advice-style.css
- index.html
> Adding Reggie's Advice

- advice/nicena-advice.html
- css/nicena-style.css
- index.html
Hello,
I was wondering if I might add my advice to the page? I primarily adjusted the styling to show another format/layout/color theme. Also, I am wondering if some of my sections would have been better as divs? Let me know, as feedback would be helpful.
Thank you,
Nicena
> Nicena's advice

- advice/meghanirish-advice.html
- css/meghanirish-advice.css
- index.html
> Added Meghan Irish's advice page

- advice/brooks-advice.html
- css/brooks-advice.css
- index.html
> Add Brook's advice page

- advice/alden-advice.html
- css/alden-styles.css
- index.html
Hi, 
I'm Alden and this is my advice page.
Thanks!
> aldens advice page

- advice/zachary-advice.html
- css/zachary-style.css
- index.html
Hi,
I just added my advice page, update my page to the main index.html
Please review.
Thanks.
> adding Zachary's advice

- advice/melissar-advice.html
- css/melissar-advice.css
- index.html
> Add Melissa's advice

- advice/thejett-advice.html
- css/thejett-style.css
- index.html
just reviewing how to GIT it done :)
> added my advice files

- advice/courtney-advice.html
- css/courtney-advice.css
- index.html
Skillcrush assignment for 105!
> Courtney Advice

- advice/juliapann-advice.html
- css/juliapann-styles.css
- index.html
> created julia's advice and added a touch of style

- advice/shannonm-advice.html
- css/shannonm-advice.css
- index.html
> Shannonm advice

- advice/aaron-advice.html
- css/aaron-advice.css
- index.html
I am pleased to add my sage wisdom to the ongoing collection! I also cleaned up a bit as referenced in my other commits. I hope I didn't overstep my bounds, but the neat freak side of me kicked in, and my gut tells me that people won't mind me cleaning up their code for free...?
> More advice comin' atcha

- advice/richc-advice.html
- css/richc-style.css
- index.html
The advice I will share with the rest of my classmates.
> My advice page

- advice/emilye-advice.html
- css/emilye-styles.css
- index.html
Sharing advice and trying out responsive coding before I actually start that lesson at the same time.
> Add Emily's advice

- advice/alannamoya-advice.html
- css/alannamoya-advice.css
- index.html
Some advice I would love to share
> Add Alanna's advice

- advice/maureen-advice.html
- css/maureen-advice.css
- index.html
> Maureen advice

- advice/magali-advice.html
- css/magali-advice.css
- index.html
Please see this request to merge with my adds :) thank you!
> created magali files and updated main html

- advice/tams-advice.html
- css/tams-styles.css
- index.html
Advice that I would like to share.
> Adding Tam's advice

- advice/phoebe-advice.html
- css/phoebe-advice-styles.css
- index.html
Some advice I'd like to share!
> Add Phoebe's advice

- advice/heathyr-advice.html
- css/heathyr-styles.css
Would love to replace the previous page with this corrected one - please and thank you :)
> fixed footer & cleaned up CSS

- advice/annika-advice.html
- css/annika-advice.css
- index.html
I added HTML and CSS for my advice and a link in the main index.html file.
> Add Annika's Advice 

- advice/artemis-advice.html
- css/artemis-advice-style.css
- index.html
This commit creates new page Artemis-advice on index.html.
> created artemis advice page

- advice/masahx-advice.html
- css/masahx-style.css
- index.html
I added page, it has links to pictures (labeled for noncommercial reuse), is it ok?
> Masha's advice

- advice/julianburns-advice.html
- css/julianburns-styles.css
- index.html
This is my amazing pull request. Please accept! Pretty please! Cherry on top!
> Julian's Pull Request

- advice/tannie-advice.html
- css/tannieadvice-styles.css
- index.html
Would like to add on Tannie's advice page!
> Add Tannie's advice

- advice/valbel-advice.html
- css/valbel-style.css
- index.html
Added my advice css and html files and my advice link to index.html, but not when I'm creating a pull request it says "Can't automatically merge" :(
> I added my advice

- advice/erinc-advice.html
- css/erinc-style.css
- index.html
> Add Erin's Advice

- advice/michellejen-advice.html
- css/michellejen-advice.css
- index.html
> michellejen-commit

- advice/annaefitzgerald-advice.html
- css/annaefitzgerald-advice.css
- index.html
Here is my first edits and page creation on a cloned repo!
> Anna branch

- advice/genevievej-advice.html
- css/genevievej-styles.css
- index.html
Added my advice and practicing a pull request :)
> Add Genevieve's advice

- advice/zachn-advice.html
- css/zachn-styles.css
- index.html
Added my version of the advice page and it's custom css for this exercise.
> Added Zach N advice page and CSS styles

- advice/cristy-advice.html
- css/cristy-advice.css
- index.html
Adding some advice for fellow students
> Adding cristy's advice page

- advice/lyndsey-advice.html
- css/lyndsey-styles.css
- index.html
My new advice HTML and CSS files. I've also added a link to my new page from the index.
> adding files for lyndsey's advice page

- advice/heytherepeters-advice.html
- css/heytherepeter-styles.css
- index.html
added index.html for peters-advice and matching style sheet.
> Adding Peter's advice page

- advice/katie-advice.html
- css/katie-advice-style.css
- index.html
Can't wait to add my advice page for new skillcrushers!
> Katie's advice changes

- advice/jasonpowell-advice.html
- css/jasonpowell-advice.css
- index.html
> first-jasonpowell-advice

- advice/advice-ashley.html
- css/advice-ashley.css
- index.html
Hello, this is my submission for Skillcrush 105 'Working with Others via Github'. It includes 1 html page, a css file, and an update to the main index.html (linking to my page). Thanks!
> Creating 'Ashley's Advice Page' for Skillcrush 105 project

- advice/josephjewell-advice.html
- css/josephjewell-advice.css
- index.html
adding my advice html and styles
> adding my advice html and css page

- advice/rosemary-advice.html
- css/rosemary-advice.css
- index.html
> Adding Rosemary-advice files

- advice/wgjd-advice.html
- css/wgjd-advice.css
- index.html
Practicing submitting a pull request.
> created and updated my individual advice-practice-html files

- advice/lwoods-wisdom.html
- css/lwoods-wisdom.css
- index.html
The advice isn't new but it is purple, and I added myself to the main html page. I don't remember if I was supposed to but I'm there :)
> Lwoods wisdom

- advice/emina-advice.html
- css/emina-style.css
- index.html
My Skillcrush advice that I would like to share
> Emina's advice

- advice/daniela-advice.html
- css/daniela-advice.css
- index.html
My advices which I would like to share.
> Add Daniela's advice

- advice/evanar-advice.html
- css/evanar-advice.css
- index.html
Some advice I would like to share...
> add Eva Naranjo's Advice

- advice/mercedes-advice.html
- css/mercedes-advice.css
- index.html
I added the html and css files for this exercise. 
I hope they are ok!
Thanks!
> My advice html and css files

- advice/maura-mcgurk-advice.html
- css/maura-mcgurk-advice.css
- index.html
Hello,
I'm submitting my html and css files for the Newbie Advice page.
Thanks and Cheers!
Maura
> Mcgurk 101

- advice/jsoubs-advice.html
- css/jsoubs-advice.css
- index.html
> Add JSoubs Advice

- advice/madelinegrdinas-advice.html
- css/madelinegrdina-style.css
- index.html
I'm not entirely sure if this is ending up where I want it--but I think I'm asking to be pulled into the main Skillcrush repo?
> Adding Madeline's advice files

- advice/abowler-advice.html
- css/abowler-advice.css
- index.html
Here is my version of the advice project.
> added abowler advice

- advice/lucyparker-advice.html
- css/lucyparker-advice.css
- index.html
> Added sample advice page

- advice/nwchang-advice.html
- css/advice-nwchang.css
- index.html
Whew! My first attempt at making a pull request. Please let me know if this process worked. I still feel very foreign to the workflow, but this is fun and challenging!
> nwchang advice page 1st draft

- advice/chrislyerly-advice.html
- css/chrislyerly-advice.css
- index.html
Added Chris Lyerly's advice edits!
> Add Chris Lyerly's advice

- advice/carrie-advice.html
- css/carrie-styles.css
- index.html
Please review and let me know what you think!  This is my second time taking this class after changing OS from PC to Mac and also being away for awhile. I must say, I remember struggling quite a bit and getting lost along the way the first time I did this. I'm not saying it was a breeze, but this time was certainly easier having been through everything once before.
> Advice files

- advice/rebecca-advice.html
- css/rebecca-advice-style.css
- index.html
A tiny bit of advice for when things get tough
> Please add Rebecca's advice 

- advice/robertpannell-advice.html
- css/robertpannell-advice.css
- index.html
Just some advice for new programmers like me!
> Added Roberts Files

- advice/marshchick-advice.html
- css/marshchick-advice.css
- index.html
added some marshchick advice about never giving up
> first edits

- advice/jenns-advice.html
- css/jenns-advice.css
- index.html
> Add Jenn's advice

- advice/veronica-advice.html
- css/veronica-advice.css
- index.html
> add veronica's advice to skillcrush 105-practice project

- advice/alma-advice.html
- css/alma-advice.css
- index.html
> Add Alma's advice

- advice/emilydougan-advice.html
- css/emilydougan-styles.css
- index.html
> New Advice Page

- advice/natasha-advice.html
- css/natasha-style.css
- index.html
Added natasha-advice.html
Added natasha-style.css
Updated index.html with link to natasha.advice.html
> Add Natasha's files

- advice/jorynicole-advice.html
- css/jorynicole-advice.css
- index.html
Request to merge jory's advice page
> jorys-advice-page-add

- advice/zacadvice.html
- css/zacadvice.css
- index.html
Here is my practice for Skillcrush 105!!
> Added new files

- advice/kalebsutherland-advice.html
- css/kalebsutherland-styles.css
- index.html
I'm submitting my first pull request for Skillcrush 105!
> created base html and css

- advice/flanice-advice.html
- css/flanice-styles.css
- index.html
> add flanice advice to both html and css

- advice/alyson-advice.html
- css/alyson-advice.css
- index.html
Made minor changes to html + css.
> minor changes

- advice/ashleyr-advice.html
- css/ashleyr-style.css
- index.html
Added files: ashleyr-advice.html, ashleyr-style.css, and added a link to ashleyr-advice.html in the index.html file.
> Added Ashley R's Advice page

- advice/mariareadv-advice.html
- css/mariareadv-style.css
- index.html
Check out my advice page and accompanying CSS, and updated index.html file with my link
> Add Maria’s advice

- advice/casey-advice.html
- css/casey-advice-styles.css
- index.html
Added Casey's advice html, CSS styling, and updated index.html
> casey advice added

- advice/alisha-advice.html
- css/alisha-advice.css
- index.html
> Alisha's changes

- advice/swolf-advice.html
- css/swolf-advice-style.css
- index.html
Added my advice page, .css, and link to index.html
> Add Sally's Advice

- advice/kimberly-advice.html
- css/kimberly-styles.css
- index.html
Adding some advice and crossing my fingers :)
> committing my advice files

- advice/laurab_advice.html
- css/laurab_advice_style.css
- index.html
I don't quite understand why i cannot automatically merge...but here it goes...
> latest attempt

- advice/elisefolk-advice.html
- css/elise-style.css
- index.html
> added elise's advice to the page

- advice/jennylynn-advice.html
- css/jennylynn-advice.css
- index.html
> Jenny Lynn's Advice Page

- advice/mariko-advice.html
- css/mariko-advice.css
- index.html
Some advice I'd like to share!
> Mariko's Adivce

- advice/kayak-advice.html
- css/kayak-advice.css
- index.html
G'day! My name is Kayak (yes, like the watercraft) and here are my words of wisdom. I also removed some stray newlines from `./index.html`.
[Prettier](https://prettier.io/) chokes on several lines in `./index.html` due to wonky `<br>` tags. I don't know if it's appropriate for me to fix that, so I just left it.
Happy perusing!
> Kayak's advice

- advice/bobhynes-advice.html
- css/bobhynes-styles.css
- index.html
> added Bob's advice

- advice/allybassadvice.html
- css/allybassadvice.css
- index.html
> Allybassadvice

- advice/karlab-advice.html
- css/karlab-advice.css
My first pull request on my advice. Please let me know if I need to do anything else.
Thank you!
> karla b changes

- advice/claregivesadvice.html
- css/claregivesadvice.css
- index.html
> Created Clare's advice html and css files

- advice/gillian2-advice.html
- css/gillian2-style.css
- index.html
Did this exercise a second time to reinforce the workflow principles!
> first commit for gillian2

- advice/misti-advice.html
- css/misti-style.css
- index.html
Hi! I completed this assignment! Thanks!!
> advice works edit

- advice/melissalux-advice.html
- css/melissalux-style.css
- index.html
Dear Code Goddesses up the cloud,
Let me have done this exercise correctly.
Yours truly,
Melissa
> Xullem code

- advice/jillys-advice.html
- css/jillys-styles.css
- index.html
Here is my second attempt at doing this. Hopefully this time I got it. I added the link to the main page and worked on utilizing branches.
> Jilly 105 practice

- advice/coriannrix-advice.html
- css/coriannrix-advice.css
- index.html
Did a pretty basic page for my advice, but hope it helps people out! :)
> Added my advice page, with CSS and added link to index.html

- advice/kelly-advice.html
- css/kelly-style.css
- index.html
> kelly-advice

- advice/stanny-v-advice.html
- css/stanny-v-advice.css
- index.html
It`s either this or my finger.
> added my advice

- advice/amanda-advice.html
- css/amanda-advice.css
- index.html
added amanda-advice html and css files and linked from index
> added amanda-advice html and css files and linked from index

- advice/gioia-advice.html
- css/gioia-advice.css
- index.html
Hello, could you please check my "advice"?
Thank you!
> gioia's advice

- advice/nates-advice.html
- css/nates-styles.css
- index.html
First pull request for 105 project.
> Redesigning the advice page from the ground up

- advice/sandral-advice.html
- css/sandral-style.css
- index.html
Hi,
Changes made based on feedback. Removed my personal css file link from the index.html file and placed it in my personal .html advice file instead. Updated the css a little to match the advice page.
> updated css link and personal css file

- advice/bethw-advice.html
- css/bethw-styles.css
- index.html
> my changes

- advice/sophiezinda-advice.html
- css/sophiez-advice.css
- index.html
> sophie's edits

- advice/michelles-advice.html
- css/michelles-advice.css
- index.html
> add MichelleS's new advise page and links with index page

- advice/kelseyjune-advice.html
- css/kelseyjune-advice.css
- index.html
Created advice html page with corresponding css styles page and updated the main site index.html page to include link to my advice page.
> Add Kelsey June's advice

- advice/mcruz-advice.html
- css/mcruz-style.css
- index.html
Hello!
This is my first time making a pull request. Thank you for reviewing this for me.
Have a great day!
Marlene
> 105 experiments

- advice/javish-advice.html
- css/javis-advice.css
- index.html
Adding javier advice link into index.html, adding javis advice css , adding javish-advice
> Adding javis advice

- advice/justinledbetter-advice.html
- css/justinledbetter-advice.css
- index.html
> added CSS and new HTML page for Justin ledbetter, updated Index as well

- advice/katecherie-advice.html
- css/katecherie-style.css
- index.html
Hello, 
I have added an advice page by katecherie to this project with some advice i'd love to share! 
Cheers, 
Kate
> created new advice html and css by katecherie

- advice/jhuff-advice.html
- css/jhuff-styles.css
- index.html
Added jhuff-advice.html in advice folder. Added jhuff-styles.css in css folder. Added link to jhuff-advice.html in index.html.
> Added Jess/Jhuff's advice

- advice/forrest_held-advice.html
- css/forrest_held-style.css
- index.html
Skill Crush Merge and Pull Lesson
> add forrest held's advice

- advice/miranda-advice.html
- css/miranda-advice.css
- index.html
Hopefully this worked and updated the index.html file with the link! Fingers crossed :)
> adding index update

- advice/nikkis-advice.html
- css/nikkis-styles.css
- index.html
> Added Nikki's advice

- advice/amandab-advice.html
- css/amandab-advice.css
- index.html
> Add AmandaB advice page

- advice/aaron-advice.html
- advice/sunilbhavsar-advice.html
- css/sunilbhavsar-advice.css
- index.html
Hello! check out my code! any feedback would be nice!
> new-branch

- advice/mai-advice.html
- css/mai-advice.css
- index.html
I added mai-advice page and linked it to the main page
> created and added mai-advice page

- advice/sarahb-advice.html
Created an advice file to add!
> created html file

- advice/michaelh-advice.html
- css/michaelh-style.css
- index.html
thank you for any feedback!
michael
> michael's advice update

- advice/amber-rose-advice.html
- css/amber-rose-advice.css
- index.html
WORKING WITH OTHERS VIA GITHUB
STEP 5 OF 9: MAKE A CHANGE THEN PUSH TO YOUR REPO
> advice added

- advice/tdm-advice.html
- css/tdm-css.css
- index.html
> added new files - TDM's advice

- advice/tonydnguyen-html.html
- css/tonydng-css.css
- index.html
Please! double check my new page. Thanks
> updated Tony D Nguyen's page

- advice/advice-tonye.html
- css/tonye-css.css
- index.html
Made a few changes I would like to add.
> changes to index and new files added

- advice/maus-advice.html
- css/maus-advice.css
- index.html
Hi, this is my version of practicing forking, merging with upstream repo etc. : )
> Practice branch

- advice/vionnesha-advice.html
- css/vionnesha-style.css
- index.html
Some advice I would love to share !
> adding vionnesha html and css

- advice/hanming-advice.html
- css/hanming-advice.css
- index.html
> Add Hanming's advice

- advice/yoshi-advice.html
- css/yoshi-style.css
- index.html
> Add Yoshi's advice

- advice/lauriebean-advice.html
- css/lauriebean-advice.css
- index.html
Submitting my advice changes pull request
> committing advice files to branch

- advice/candicezakariya-advice.html
- candicezakariya-advice.html
- css/candicezakariya-style.css
- index.html
> Candice experiment

- advice/tort-advice.html
- css/tort-style.css
- index.html
First pull request ever yaaay.
> add tort-advice.html and tort-style.css

- advice/corinna-advice.html
- css/corinna-styles.css
- index.html
> Add Corinna's advice

- advice/patrick-advice.html
- css/patrick-style.css
- index.html
I would like to add my Advice :)
> added Patrick's Advice

- advice/xandermayor-advice.html
- css/xandermayor-style.css
- index.html
Added my css and html files, added link and missing line break to index.html!
> My contributions

- advice/tanyaself-advice.html
- css/tanyaself-advice.css
- index.html
> Add Tanya's advice

- advice/ellie-advice.html
- css/ellie-advice.css
- index.html
> Adding Ellie's advice

- advice/Jlynn-advice.html
- css/Jlynn-advice.css
- index.html
> Added Jlynn-advice

- advice/winnie-advice.html
- css/winnie-advice.css
- index.html
Updating with Winnie's advice.
> added Winnie's advice and updated index with link

- advice/davide-advice.html
- css/davide-advice.css
- index.html
Hello!,
I would like to know if I did everything correctly!
> adding Davide's advice

- advice/fannens-advice.html
- css/fannens-styles.css
- index.html
There are two commits because I forgot to pull to check if there were any changes.
> Adding advice

- advice/akgoen_advice.html
- css/akgoen-advice.css
- index.html
> Add Alexandra's advice

- advice/michael-sampson.html
- css/michael-sampson.css
- index.html
> added michael-sampson advice

- advice/jennig-advice.html
- css/jennig-advice.css
- index.html
practicing GitHub with 105-practice advice!
> jennig advice page yay

- advice/marko-advice.html
- css/marko-style.css
- index.html
> added Marko's advice

- advice/jenilyn-advice.html
- css/jenilyn-styles.css
- index.html
Please add my stuff to your stuff. Thank you!
> Add Jenilyn's Advice

- advice/advice-heatherco8.html
- css/advice-heatherco8.css
- index.html
Adding my advice to the mix! Also, I noticed that the person's link under mine (Devon's advice) on the index.html file has an incorrect path to his files, so it doesn't link to anything. I didn't change anything because I didn't want to mess anything up, but thought I'd share in case you want to fix it.
> Adding Heatherco8's files

- advice/carol-advice.html
- css/carol-advice.css
- index.html
Some advice I would like to share
> Created Carol's html and css files and linked to index.html

- advice/laurenh-advice.html
- css/laurenh-advice.css
- index.html
> added laurenh advice html/css

- advice/carolynwalker-advice.html
- css/carolynwalker-style.css
- index.html
> updated advice page

- advice/meredithmischler-advice.html
- css/meredithmischler-styles.css
- index.html
This is some advice I would like to share with future Skillcrushers. Thank you!
> Add Meredith Mischler's Advice

- advice/christinenicole-advice.html
- css/christinenicole-styles.css
- index.html
Hello!  Would love to add my page to the advice.  Thanks!
> Add Christine branch

- advice/claudiacachayosorio.html
- css/claudiacachayosorio.css
- index.html
> created my page, added link on index and fixed typo

- advice/bellas-advice.html
- css/bellas-advice-style.css
- index.html
This is the advice page requested for the 105-practice site
> bellas advice page

- advice/kariswenson-advice.html
- css/kariswenson-styles.css
- index.html
Added my advice for new coders!
> Add Kari Swenson's advice

- advice/morgan-advice.html
- css/morgan-style.css
- index.html
> 105 practice edits

- advice/advice-blair.html
- css/advice-blair.css
- index.html
made changes what do you think?
> updated index and created a blair advice html and css

- advice/tammy-advice.html
- css/tammy-style.css
- index.html
Hi, I am re-doing this lesson, as apparently, I didn't retain the information the first time around.
> second-try

- advice/lance-advice.html
- css/lance-advice.css
- index.html
- added new lance-advice.html
- added new lance-advice.css
- fix anchor closing tag
> lance-105-PR

- advice/advice-emaggen.html
- css/advice-emaggen.css
- index.html
hi! i've added my advice page and css
> added my advice page and css

- advice/juliannalivecchi-advice.html
- css/juliannalivecchi-advice.css
- index.html
> finished my advice page html and css

- advice/amandamac-advice.html
- css/amandamac-advice.css
- index.html
> added amandas advice

- advice/meganwillow-advice.html
- css/meganwillow-styles.css
- index.html
Submitting my advice page. Thanks.
> add megan advice

- advice/bsh-advice.html
- bsh-advice.html
- css/bsh-style.css
- index.html
Here's my advice code ready to be merge!
> Bsh version

- advice/troys-advice.html
- css/advice-troy-styles.css
- index.html
Looking forward to seeing what happens when I click this request!  Everyone sure gave great advice!
> added Troy's Advice to Advice Page

- advice/sabinev-advice.html
- css/sabinev-advice.css
- index.html
Some new advice to add into the mix
> added my advice page sabinev-advice

- advice/advicefromhollyllama.html
- css/advicefromhollyllama-style.css
- index.html
Droppin' some wisdom here, include at your discretion.
> Add HollyLlama's Advice

- advice/calogero-advice.html
- css/calogero-advice-style.css
- index.html
> Updated Calogero's advice

- advice/magda-advice.html
- css/magda-advice.css
- index.html
> Add Magda's advice page

- advice/kelliem-advice.html
- css/kelliem-advice.css
- index.html
> add kellie's advice html & css

- advice/geordieeasterbrook-advice.html
- css/geordieeasterbrook-advice.css
- index.html
Excited to request my first pull! Hope everything looks in order!
> created advice page and linked to primary index

- advice/annabel-advice.html
- css/annabel-style.css
- index.html
Hi, I'm with Skillcrush under anutabel@yahoo.ca email. 
My GitHub is under annanski@outlook.com
It says "Can't automatically merge"
I forked the original repository over 2 weeks ago, so I think index.html got more names added. I had a merge conflict when merging upstream.
> annabel advice added

- advice/samdexter-advice.html
- css/samdexter-style.css
- index.html
Submitting my first pull request! Here I personalized the sample code provided a bit.
> personalization

- advice/emilydavis-advice.html
- css/emilydavis-styles.css
- index.html
Replace Skillcrush with your name here
> made changes

- advice/melissajohnson-advice.html
- css/melissajohnson-styles.css
- index.html
Advice coming from someone who was afraid of merge conflicts but then learned by working with dev teams why it's necessary to get comfortable with them. 🙂
> Add Melissa Johnson's advice

- advice/amandat-advice.html
- css/amandat-advice.css
- index.html
> added advice

- advice/beth3advice.html
- css/beth3-styles.css
- index.html
I wonder if it will not automatically merge because of some changes made to the index.html file. I believe this will not interfere with the addition of my name (Beth 3) to the list on the main index.html file, nor with the code I have associated with it - html, css.
> added Beth3 to index, advice and styles

- advice/sarienne-advice.html
- css/sarienne-advice.css
- index.html
Added my advice as per the assignment. Waiting for feedback.
> added link to index.html, added my css and html files

- advice/mariahl-advice.html
- css/mariahl-advice.css
- index.html
Here's my addition for review/approval.
> Mariahl advice

- advice/suzanneadvice.html
- css/suzanneadvice-style.css
- index.html
Adding some advice I'd like to share with future Skillcrushers
> Add's Suzanne's advice

- advice/jace-advice.html
- css/jace-advice.css
- index.html
> jace's advice

- advice/aimeeadvice.html
- css/aimeeadvice.css
- index.html
practicing how to submit a pull request for 105 lesson
> practicing for 105 lesson

- advice/tonys-advice.html
- css/tonys-advice.css
- index.html
Did not add much style due to time crunch, but more to come from me!!
> Newversion

- advice/gaby-advice.html
- css/gaby-advice.css
- index.html
Some advice I'd love to share.
> 105 experiment

- advice/roni-advice.html
- css/roni-advice.css
- index.html
learning to add branches and some advice.
> testing branch changes

- advice/rodricode-advice.html
- css/rodricode-style.css
- index.html
Some advice I would like to share
> rodricode's advice and styling

- advice/garrettnoble-advice.html
- css/garrettnoble-advice.css
- index.html
> new commit

- advice/aishas-advice.html
- css/aishas-advice-styles.css
- index.html
Here is my styled advice :D please add if it's okay!
> Add Aisha's Advice

- advice/laurenlavoie-advice.html
- css/laurenlavoie-styles.css
- index.html
> Add Lauren's advice!

- advice/nicolettehinds-advice.html
- css/nicolettehinds-styles.css
- index.html
I added my advice html and css files as well as added the link to my html file to the index.html file.
> added my advice page to the folders

- advice/javier-advice.html
- css/javier-style.css
- index.html
> Practice makes perfect

- advice/kayla.html
- css/kayla.css
- index.html
Here's my changes for my page addition.
> Kayla Serbus' changes

- advice/corey-advice.html
- css/corey-styles.css
- index.html
> Add Corey's advice

- advice/debora-advice.html
- css/debora-advice.css
- index.html
Added my short advice page! :-)
> debora's advice

- advice/grettagoldstein-advice.html
- css/gretta-style.css
- index.html
My advice! I didn't code it way too fancy as I'm sneaking in this course during my day job (shhh :) ) but it'll do the trick!
> Experiement

- advice/bethF-advice.html
- css/BethF-advice.css
- index.html
I would love to share some advice with you.
> added Beth F advice

- advice/wdnelson-advice.html
- css/wdnelson-styles.css
- index.html
Adding my advice. I also cleaned up some of the tabs in the original index.html... (couldn't help myself) =)
> Adding WD Nelson's advice

- advice/marina-advice.html
- css/marina-advice.css
- index.html
> Marinas advice

- advice/emilysprague-advice.html
- css/emilysprague-advice.css
- index.html
> added emily sprague's advice

- advice/alasdairselmes-advice.html
- css/alasdairselmes-styles.css
- index.html
> Add Alasdair's Advice

- advice/jon-advice.html
- css/jon-advice.css
- index.html
added my own advice html/css and cleaned up the index.html file a little.... just saw a few things that were off.
> added jon's advice files

- advice/advice-marcy.html
- css/marcy-styles.css
- index.html
> adding advice-marcy page

- advice/sebrina-advice.html
- css/sebrina-advice.css
- index.html
I added my own advice page to the main advice page for newbies!
> added my advice page

- advice/evalarkin-advice.html
- css/evalarkin-advice.css
- index.html
An advice page that I would like to add.
> Eva's advice page added and styled

- advice/seanbarile-advice.html
- css/seanbarile-styles.css
- index.html
> Sean Barile's Advice

- advice/rias-advice.html
- css/rias-advice.css
- index.html
> added advice html advice css and index link

- advice/amy-advice.html
- css/amy-advice.css
- index.html
Hi made these edits to add my advice to the site, hope you like them!!!
> amy advice edits

- advice/alejandro-advice.html
- css/alejandro-style.css
- index.html
Adding my advice to the collection!
> Updated html and css

- advice/jentrekin.html
- css/jentrekin.css
- index.html
> Jessica Entrekin

- advice/sarahcate-advice.html
- css/sarahcate-styles.css
- index.html
Some advice, but with my own style!
> added my advice html and css

- advice/jenls-advice.html
- css/jenls-advice.css
- index.html
> updated HTML with my name and created css

- advice/advice-stephaniegmalek.html
- css/advice-stephaniegmalek-style.css
- index.html
The advice I would love to share
> Stephanie G's Advice files added

- advice/jordanna-advice.html
- css/jordanna-advice.css
- index.html
Updated info in HTML document and added styling to CSS document
> changed info in advice.html and added styling with advice.css

- advice/katpayne-advice.html
- css/katpayne-style.css
- index.html
> my first commit

- advice/theookada-advice.html
- css/theookada-style.css
- index.html
> Theo Okada Advice html and css

- advice/cj-advice.html
- css/cj-advice.css
- index.html
> cjs advice

- advice/mellisoradvice.html
- css/mellisor-advice.css
- index.html
First pull request! (fingers crossed)
> michelle's advice addition

- advice/adanna-advice.html
- css/adanna-advice.css
- index.html
Some advice I would love to share with the world
> Adanna's advice

- advice/nikela-advice.html
- css/nikela-advice-styles.css
- index.html
> Advice branch

- advice/joshals-advice.html
- css/joshals-style.css
- index.html
Would like to share my suggestions
> Skillcrush repo joshals

- advice/dani-advice.html
- css/dani-style.css
- index.html
> created html and css files

- advice/amys-advice.html
- css/amys-advice.css
- index.html
I thought I fixed the merge conflict, not sure why it shows up here or why it ever showed up in the first place.
> create My Advice

- advice/francesca-advice.html
- css/francesca-styles.css
- index.html
> add Francesca's advice

- advice/kayla_advice.html
- css/kayla_advice.css
- index.html
There is advice that I would love to share with you!
> Kayla's advice

- advice/advice-katl.html
- css/advice-katl.css
- index.html
Just some advice for new coders
> Adding advice-katl html and css files

- advice/srm-advice.html
- css/srm-styles.css
- index.html
Sara- advice I would like to share
> Add Sara's Advice

- advice/advice-suthat.html
- css/advice-suthat.css
- index.html
> My pull request

- advice/trvirtual-advice.html
- css/trvirtual-styles.css
- index.html
> Adding my advice page

- advice/maeeast-advice.html
- css/maeeast-advice.css
- index.html
Leaving my advice for posterity
> Add maeeast's advice

- advice/valmejia-advice.html
- css/valmejia-advice.css
- index.html
Some advice I would love to share.
> advice page

- advice/sandy-advice.html
- css/sandy-style.css
- index.html
I tried. I think I need to take this advice so I don't give up.
> Advicebranch

- advice/dianalee-advice.html
- css/dianalee-advice.css
- index.html
I'm still not sure i understand this! I'll have to review this topic!!!
> added personal advice page and style sheet

- advice/jana-advice.html
- css/jana-advice.css
- index.html
Hello! This is my first pull request as part of the 105- practice. Be kind :)
Jana xo
> Janabranch

- advice/janas-advice.html
- css/janas-advice.css
- index.html
Some advice I would like to share
> Janas experiment

- advice/adriannepadua-advice.html
- css/adpad-style.css
- index.html
I'm contributing some advice to the master list.
> Added a new advice page for Adrianne Padua

- advice/naja-advice.html
- css/naja-advice.css
- index.html
Hi,
I add new file naja-advice.htm and naja-advice.css and also I put link in the index.html.
This is my first try:)
Best, Naja
> First practice

- advice/adam-advice.html
- css/adam-css.css
- index.html
Practice exercise for Class 105
> Add html page, and css style sheet for Adam.

- advice/cadearmstrong.html
- css/cadearmstrong.css
- index.html
> added cade armstrong

- advice/annmariesantos-advice.html
- css/annmariesantos-advice.css
- index.html
This is my advice page.  I kept it simple, for now. :-)
> coded and styled my advice page

- advice/cy-advice.html
- css/cy-advice.css
- index.html
> added css and html

- advice/darwin-advice.html
- css/darwin-styles.css
- index.html
> Add Allison's advice

- advice/elan-advice.html
- css/elan-advice.css
- index.html
adding elan advice and css styles
> added elan advice and css styles

- advice/tomo-advice.html
- css/tomo-advice.css
- index.html
Hello.
I added Tomo's advice link. Hope that you can accept it!
Tomo :)
> Add request - Tomo's advice

- advice/sonay-advice.html
- css/sonay-advice.css
- index.html
> sonay-advice

- advice/jimmy-shandogs-advice.html
- css/jimmy-shandogs-styles.css
- index.html
Advice I once was given, I now give.
> added my 2 cents.

- advice/advice-brade.html
- css/advice-brade.css
- index.html
Added Brad Advice html and styles and updated main index.html
> Brad advice

- advice/megan-denman.html
- css/m-denman-style.css
- index.html
> my advice page and styles added

- advice/denisemeagher-advice.html
- css/denisemeagher-styles.css
- index.html
> Dsm new pages

- advice/veras-advice.html
- css/veras-advice.css
- index.html
> added new file vera's advice

- advice/stepheugene-advice.html
- css/stepheugene-style.css
- index.html
Some advice to share to future Skillcrushers.
> steph eugene

- advice/trevorpeugh-advice.html
- css/trevorpeugh-styles.css
- index.html
Added some chaotic flair to h1 and p tags.
> trevor-advice-html-css

- advice/jolferz-advice.html
- css/jolferz-advice.css
- index.html
> Jolfer'z advice html and css

- advice/chelseaday-advice.html
- css/chelseaday-styles.css
- index.html
Please add my advice or let me know if it needs to be changed. Thank you!
> Added Chelsea Day's Advice

- advice/annierimbach-advice.html
- css/annie-advice.css
- index.html
> added annie rimbach

- advice/robowen-advice.html
- css/robowen-styles.css
- index.html
Please review these files for addition to skillcrush/105-practice. Thank you..
> Added CSS & Advice.html files

- advice/robs-advice.html
- css/robs-advice.css
- index.html
Hey, I'm leaving my advice index in the advice folder "robs-advice" with complimenting css in the css file. I've also added a link to my html page on the primary index.html page.
Thanks for the practice
> added rob's advice files

- .gitignore
- advice/sarahg-advice.html
- css/sarahg-advice.css
- index.html
second request. unable to merge previous branch.
> 105 practice branch

- advice/ashrenolarte-advice.html
- css/ashrenolarte-advice.css
- index.html
Some advice I like to tell myself when I come across any obstacles or have doubts.
> Add Ashren's Advice

- advice/jaredps-advice.html
- css/jaredps-style.css
- index.html
I indented the previous link's code and added my own.
> Jared ps branch

- advice/caseyX-advice.html
- css/caseyX-advice.css
- index.html
> Casey advice

- advice/coltonorgan-advice.html
- css/coltonorgan-advice.css
- index.html
> Added Colton's Advice

- advice/steves-advice.html
- css/steves-advice-style.css
- index.html
A wee bit of developing advice to share.
> Adding Steve's Advice Files

- advice/noelarzola-advice.html
- css/noelarzola-styles.css
- index.html
Updated index to include my page with some quotes and advice; added my html and css files
> Added Noel Arzola's Advice

- advice/karinapacheco-advice.html
- css/karinapacheco-advice.css
- index.html
Here is some advice I would like to share.
> Add Karina's advice

- README.md
- advice/ericl-advice.html
- css/ericl-advice.css
- index.html
> my advice changes that are from ericl

- advice/kaitlyn-advice.html
- css/kaitlyn-styles.css
- index.html
> added my advice section

- advice/ema-jensen-advice.html
- css/ema-jensen-style.css
- index.html
> ema's advice addition

- advice/mick-s-advice.html.html
- css/mick-s-advice.css.css
- index.html
> added html and css to repo

- advice/csutton-advice.html
- css/csutton-advice.css
- index.html
> Added CSutton Advice

- advice/rosiepi-advice.html
- css/rosiepi-styles.css
> Added Rosie Pi advice link

- advice/jstar-advice.html
- css/jstar-advice.css
- index.html
initial upload of j-star advice
> J star Advice

- advice/flavia-advice.html
- css/flavia-advice.css
- index.html
> Created my advice files

- advice/nicolecanovas-advice.html
- css/nicolecanovas-styles.css
- index.html
Some advice I would love to share.
> Add Nicole's Advice

- advice/christinasadvice.html
- css/christinasadvice.css
- index.html
Hey everybody,
man this is confusing *sweat* But I made it this far so no giving up. As instructed I created my own little advice page with html & css and linked it to the index.html
I think it looked fine and so far it seems to be working.....
I'm looking forward to your feedback :)
> christinas

- advice/ypadron-advice.html
- css/ypadron-styles.css
- index.html
My contribution to the advice page.
> Add ypadron's advice

- advice/sikio-advice.html
- css/sikio-advice.css
- index.html
My advice page for Skillcrush.
> Added my advice index and css files

- advice/bebes-advice.html
- css/bebe-advice.css
- index.html
Here is some advice from Bebe.
> Create advice page

- advice/carrierobbins-advice.html
- css/carrierobbins-styles.css
- index.html
> created and styled advice page

- advice/sara-advice.html
- css/sara-advice.css
- index.html
Added my advice to our long list!
> Advice add

- advice/igicruz.html
- css/igicruz-style.css
- index.html
> changed layout

- advice/elises-advice.html
- css/elises-style.css
- index.html
> created new advice page

- advice/nicole-walden-advice.html
- css/nicole-walden-advice.css
- index.html
> Add Nicole Walden's Advice

- advice/kelsi-advice.html
- css/kelsi-styles.css
- index.html
> Kelsi's Advice Page

- advice/klamke-advice.html
- css/klamke-advice.css
- index.html
> Klamke - Updated html and css

- advice/melparker-advice.html
- css/melparker-style.css
- index.html
Added melparker-advice.html and melparker-style.css.
> updated files

- advice/heatherbee-advice.html
- css/heatherbee-style.css
- index.html
It's not pretty - just wanting to get practice with Git/GitHub & pull requests
> addition of heatherbee's advice

- advice/egbert-advice.html
- css/egbert-advice.css
- index.html
Added html, css for advice page.  Also added link in master html to access new advice page
> added carol egbert advice

- advice/tomomi-advice.html
- css/tomomi-advice.css
- index.html
> Tomomi's advice 

- advice/danas-advice.html
- css/danas-advice.css
- index.html
> added Dana's advice webpage

- advice/christopherbean-advice.html
- css/christopherbean-style.css
- index.html
I think I MIGHT have done this correctly! My power went out yesterday when I started doing this!
In the spirit of actual collaboration my tweaks:
-add my own advice for newbies via christopherbean-advice.html
-added my own styling via christopherbean-style.css
-added a link to my advice page in index.html
Hope this works! Thanks!
> Christopher's first github collaboration attempt

- advice/ems-advice.html
- css/ems-advice-style.css
- index.html
I'm adding my advice - still a little unsure
> Em Thomson

- advice/joel-advice.html
- css/joel-style.css
- index.html
I add on Joel's advice for new programmers.
> Added Joel's Advice

- advice/lilys-advice.html
- css/lilys-advice.css
- index.html
some advice that i would really love to share!
> added lilys advice

- advice/phila-advice.html
- css/phila-advice.css
- index.html
> adding phil's stuff

- advice/lonemortensen-advice.html
- css/lonemortensen-styles.css
- index.html
Hi! I added my advice/style files and updated index file with my link. 
- I synced my forked repo/merged with upstream remote repo a few days ago. Not sure if I was supposed to sync again immediately before creating this pull request (I didn't)??
Thanks :) 
Lone
> added my advice and styles files, and added link to index file

- advice/diana-hinchcliffe-advice.html
- css/diana-hinchcliffe-advice.css
- index.html
I did this exercise a while ago but have not been able to work on the project for a while. I have gone back and did some of the exercises over again. Please take a look. Let me know if it can be merged.
> Changes made to old pull request. 

- advice/vanessuniq-advice.html
- css/vanessuniq-advice.css
- index.html
> added my advice html file and css file

- advice/billy-advice.html
- css/billy-styles.css
- index.html
testing out the pull request!!
> added own advice.html and css

- advice/suzi-advice.html
- css/suzi-advice.css
- index.html
Here is my advice edits. :) Thanks! 
Suzi
> created suzi's advice page

- advice/zoesadvice.html
- css/zoesadvice.css
- index.html
Hi there,
I am hoping that 2nd time is the charm, I would love some feedback. Last time I got my branches horribly confused :(
Z
> Zoe's Advice

- advice/Marc-A-advice.html
- css/Marc-A-style.css
- index.html
Finishing the Forking Workflow
> Marc Arbones' Advice

- css/zoe-s-advice.css
- index.html
- zoe-s-advice.html
Hi,
Let me know if this all in correct?
Z
> Zoe-S-Advice

- advice/sheila-advice.html
- css/sheila-advice.css
- index.html
> sheilas advice page

- advice/tiffin-advice.html
- css/tiffin.css
- index.html
Updated copy, updated colors, fixed a space on the index page
> merge advice and master

- advice/kaylab-advice.html
- css/kaylab-styles.css
- index.html
My advice to share with other skillcrushers
> Kayla advice

- advice/michellelui-advice.html
- css/michellelui-styles.css
- index.html
Added my contributions to the project!
> added michelle lui html and css files

- advice/brayden-c-advice.html
- css/brayden-c-advice.css
- index.html
Added Brayden C advice to project
> Create advice page with styling and add link to index

- advice/megan-o-advice.html
- index.html
added megan o advice to list of skillcrush advice
> added megan o advice

- advice/sandra-t-advice.html
- css/sandra-t-style.css
- index.html
Added the files with my personal advice
> My version of the Advice page

- advice/najihah-advice.html
- css/najihah-advice.css
- index.html
> Added Najihah's advice

- advice/jenny-line-advice.html
- index.html
I got in a mess with this one because I still had the old repo from the last time around! Lessons learned!
> Added new advice file for Jenny L

- advice/michael-s-advice.html
- index.html
> Added Michael S's advice page

- advice/abbey-advice.html
- css/abbey-advice.css
- index.html
SOOOO hoping this one works finally.. Please let me know if it does. Been driving me bonkers for weeks.
> adding abbeys advice

- advice/nancy-c-advice.html
- css/nancy-advice.css
- index.html
Please pull my branch into the 105-practice repo.
Thank you!
Nancy
> Advice Branch to Add

- advice/tom-d-advice.html
- css/style.css
- css/tom-d-advice.css
- index.html
Added a link to my advice page and the advice page
> Added tom-d-advice to the page

- advice/gael-p-advice.html
- css/gael-p-style.css
- index.html
Thank you for adding my pull request. I have learned so much so far.
> Added Gael P advice page

- advice/ellen-h-advice.html
- index.html
> Ellen advice

- advice/brittany-advice.html
- css/brittany-style.css
- index.html
Brittany's advice for beginners
> added html and css for Brittany's advice

- advice/cameron-p-advice.html
- index.html
> Added Cameron P's advice

- advice/alysia-m-advice.html
- css/alysia-m-styles.css
- index.html
I had some issues when it came to merging the master into the advice branch. It would tell me that the file was already up to date. I had to merge the advice branch into the master to get the files to merge. I'm not sure if that was the correct thing to do.
> Added alysia-m-advice.html and alysia-m-styles.css

- advice/Jordan-G-advice.html
- css/Jordan-G-style.css
- index.html
> Added Jordan G's advice page, CSS style, and link from Index

- advice/chase-ih-advice.html
- css/chase-ih.css
- index.html
> Added Chase's advice to project

- advice/lianna-b-advice.html
- index.html
I would like to add my changes to the shared repo
> Updated Advice file and linked it on index page

- advice/erica-advice.html
- index.html
Got a bit lost, not sure if I did this last step right...
> Personalized Changes

- advice/stephanie-b-advice.html
- css/stephanie-b-advice.css
- index.html
I am really feeling like I did something wrong here. Thanks for your help.
> Forking workflow assignment

- advice/sherry-h-advice.html
- index.html
> personalized advice

- advice/stefania-p-advice.html
- css/stefania-p.css
- index.html
Created  stefania-p-advice.html and stefania-p.css and added the link to my advice page on the index.html page
> Added Stefania P's advice page

- advice/claudiacachayosorio.html
Revising the 105 class, so went back to the page I already had created and just changed the year at the end.
> Updated claudiacachayosorio page's copyright date to current year

- advice/jenn-b-advice.html
- css/jenn-b-advice.css
- index.html
> Added jenn-b-advice.css and jenn-b-advice.html to index.html

- advice/deanna-davia-advice.html
- css/deanna-style-advice.css
- index.html
I had quite a bit of trouble with the forking workflow steps in the course, so hoping everything works out ok. 
Thanks!
> Advice - deanna-d

- advice/codesensei337-advice.html
- css/codesensei337-advice.css
- index.html
> Added my advice file to team advice files

- advice/erin-l-p-advice.html
- css/erin-l-p.css
- index.html
Updated index with link to my advice and added Erin L P's advice html and css files.
> Added Erin L P's advice, css and link to index

- advice/susan-gp-advice.html
- css/susangp-style.css
- index.html
> Added css and updated files for Susan GP

- advice/katie-f-advice.html
- css/katie-f-advice.css
- index.html
Changed the Advice page to be from Katie F's perspective.
> Added Katie F's Advice page

- advice/yucheng-h-advice.html
- index.html
> add yucheng-h-advice.html

- advice/Lizandra13-advice.html
- css/style-Lizandra13.css
- index.html
Added Student Advice exercise. Lizandra J R
> Added Lizandra13-advice to the master

- advice/andrew-h-advice.html
- index.html
Not exactly sure what type of comment I need to leave here, so..."hi."
> Added name to the list

- advice/amy-f-advice.html
- css/amy-f.css
- index.html
> Amy F's advice

- advice/kacey-w-advice.html
- css/kacey-w-advice.css
- index.html
I started over. I may have made it worse, but I'm hoping that it works now!
> Kacey-W-Advice

- advice/alicia-c-advice.html
- css/alicia.css
- index.html
> New advice page and updated main

- advice/jacquan-b-advice.html
- css/jacquan-b.css
- index.html
- jacquan-b.css
Added my advice link to the code.
> Added my advice link

- advice/jengreen-advice.html
- css/jeng-advice.css
- index.html
Requesting to merge Jen Green advice into the master
> Added Jen Green advice page 

- advice/natalie-mcl-advice.html
- css/natalie-mcl-advice.css
- index.html
Would like to add advice branch "Natalie-mcl-advice"
> Natalie-mcl-advice

- advice/christina-s-advice.html
- css/christina-s-style.css
- index.html
Was a little unsure about the last few steps!
> Added christina-s-advice page, associated css file and link in index

- advice/tuvy-g-advice.html
- css/tuvy-g-style.css
- index.html
> Added tuvy-g advice and styling

- advice/clare-e-advice.html
- css/clare-e.css
- index.html
Hi guys! Hope this works - thanks for all the help!
> Added clare-e-advice.html and css/clare-e.css to main page

- advice/emily-d-advice.html
- css/emily-d-styles.css
- index.html
> Added Emily D's advice

- advice/cris-c-advice.html
- css/cris-c.css
- index.html
> Cris C's advice

- advice/priscilla-p-advice.html
- index.html
Completing "Finishing the Forking Workflow", does everything look okay?
> Priscilla's Advice

- advice/mat-s-advice.html
- css/mat-s-advice.css
- index.html
I had to go over this quite a few times, almost lost my nerve.
> added stuff
